export const USER_LOGIN = 'USER_LOGIN';
export const USER_STATUS = 'USER_STATUS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CREATE = 'USER_CREATE';

export const ERRORS_MESSAGES = 'ERRORS_MESSAGES';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';

export const ADD_LOADING_ITEM = 'ADD_LOADING_ITEM';
export const REMOVE_LOADING_ITEM = 'REMOVE_LOADING_ITEM';
export const GET_LOADING_STAGE = 'GET_LOADING_STAGE';
