export const USER_LOGIN = 'USER_LOGIN';
export const USER_STATUS = 'USER_STATUS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CREATE = 'USER_CREATE';

export const ERRORS_MESSAGES = 'ERRORS_MESSAGES';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';

export const ADD_LOADING_ITEM = 'ADD_LOADING_ITEM';
export const REMOVE_LOADING_ITEM = 'REMOVE_LOADING_ITEM';
export const GET_LOADING_STAGE = 'GET_LOADING_STAGE';

export const SEARCH_OPEN_TASKS = 'SEARCH_OPEN_TASKS';
export const OPEN_TASK = 'OPEN_TASK';
export const STATUS_TASK = 'STATUS_TASK';
export const CLOSE_TASK = 'CLOSE_TASK';
export const TASK_POP_OPEN = 'TASK_POP_OPEN';
export const TASK_POP_CLOSE = 'TASK_POP_CLOSE';

export const UPDATE_TIME = 'UPDATE_TIME';

export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_FAILD = 'GET_TASKS_FAILD';

export const GET_TASK_BY = 'GET_TASK_BY';
export const GET_TASK_BY_SUCCESS = 'GET_TASK_BY_SUCCESS';
export const GET_TASK_BY_FAIL = 'GET_TASK_BY_FAIL';
